---
abstract: 'Counting utility for a file consisting of the fixed number of fields like CSV'
author:
  - 'Yasutaka ATARASHI <yakex@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300029, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-count
requires:
  YAML::Any: 0
  perl: 5.006
version: v0.0.1
